spring:
  application:
    name: news-api-project
    datasource:
      url: none
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
          - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

newsapi:
  key: 17174703f4924a0b95f4e87e578602bb

server:
  port: 8080

requests:
  topHeadlines: "https://newsapi.org/v2/top-headlines"